# freertos.mk

CSRCS += $(wildcard $(FREERTOS_DIR)/$(FREERTOS_DIR_NAME)/*.c)
CSRCS += $(wildcard $(FREERTOS_DIR)/$(FREERTOS_DIR_NAME)/portable/GCC/ARM_CM4F/port.c)
CSRCS += $(wildcard $(FREERTOS_DIR)/$(FREERTOS_DIR_NAME)/portable/MemMang/heap_4.c)

DEPPATH += --dep-path $(FREERTOS_DIR)/$(FREERTOS_DIR_NAME)/include
DEPPATH += --dep-path $(FREERTOS_DIR)/$(FREERTOS_DIR_NAME)/portable/GCC/ARM_CM4F
VPATH += $(FREERTOS_DIR)/$(FREERTOS_DIR_NAME)/include
VPATH += $(FREERTOS_DIR)/$(FREERTOS_DIR_NAME)/portable/GCC/ARM_CM4F

CFLAGS += -I$(FREERTOS_DIR)/$(FREERTOS_DIR_NAME)/include
CFLAGS += -I$(FREERTOS_DIR)/$(FREERTOS_DIR_NAME)/portable/GCC/ARM_CM4F

# $(info FREERTOS_DIR = $(FREERTOS_DIR)/$(FREERTOS_DIR_NAME))
